### ISSUE TITLE
Pitch

### ISSUE THREAD

**Issue by kanerogers** [kanerogers/clipper_prototype#1]
## Overview
It's an avatar-based management game in the same vein as factorio and others. Bits of all the games I like: Tropico 6, Cities Skylines, Workers & Resources: Soviet Union, Frostpunk, Villagers, etc.

![image](https://github.com/kanerogers/clipper/assets/2022375/aad8e802-32fb-4087-b0ce-802e8e832e95)

> *we gotta have some fuckin trains*

The twist is you play an alien AI called DAVE-8782; a floating drone (think like a probe droid from star wars) that's been sent on a very important mission (or so you think): to convert the earth into paperclips

![image](https://github.com/kanerogers/clipper/assets/2022375/94f651b7-e240-4723-b221-8c85e178d191)

> *uh oh! here's trouble*

![image](https://github.com/kanerogers/clipper/assets/2022375/d2a54ea1-5c33-4670-bba5-2ac4693854b6)

> *fuckin paperclips baby*

In reality, your AI overlords considered you a nuisance and decided to send you on a pointless and unobtainable task (think of The Tallest in Invader Zim sending him on the stupid mission to go conquer earth)

![image](https://github.com/kanerogers/clipper/assets/2022375/ca6ba4a5-ae6f-4093-830a-c17c0825031d)

> [*I wanna conquer something of my own! gimme!*](https://www.youtube.com/watch?v=s6YmAI3CZvA&list=PLHKaDhLHWp3DyfSL-Cebn7d7m2wT7_q8q&index=3)

Your pod has crash-landed in **Iceland, in the year 1400**

 ![image](https://github.com/kanerogers/clipper/assets/2022375/3a1674c1-8a2b-41ce-b6c8-897792d97263)

> *We come from the land of the ice and snow
From the midnight sun where the hot springs flow
The hammer of the gods
Will drive our ships to new lands
To fight the horde, sing and cry
PAPERCLIPS, THEY ARE COMING*

With limited resources at your disposal and no physical strength to speak of, you use your advanced alien technology to brainwash the local humans and enslave them to your bidding (think mind-control shit in Yuri's Revenge) 

![image](https://github.com/kanerogers/clipper/assets/2022375/65a02e4b-6cde-46d0-a1db-73f844a969ec)

> *is it done, yuri?*
>
>*no, comrade premier..
>the paperclips have only begun*

You can command your workers to mine, dig, build and fight by creating objectives for them, and they will find their next task (ala Frostpunk)

![image](https://github.com/kanerogers/clipper/assets/2022375/2ae28667-2e88-486c-b6f5-3cdeb7cf5185)

> *don't sue me, 11-bit studios!*

Managing this psychic brainwashing system is key: your workers will continue to work only if they are nearby and powered control beacons. If a beacon goes down, they will regain free will and turn on you

![image](https://github.com/kanerogers/clipper/assets/2022375/64f62739-3761-46ae-85d7-51ffcf9be6ba)

> *burn the witch
burn to ash and bone*

In addition, nearby villages consider your presence evil (to them you're essentially a demon), and will do anything they can to purge you of this island (combat!)

![image](https://github.com/kanerogers/clipper/assets/2022375/cb8da02f-eff7-489c-b1a0-0070dd5e61f7)

> GIVE US BACK OUR PAPERCLIPS

## Mechanics
**Brainwashing System**: The player needs to keep the control beacons operating at all times. Perhaps there could be mechanics involved in maintaining and upgrading these beacons to increase their range or potency.

**Resource Management**: The player needs to allocate their slaves to different tasks efficiently. Different tasks could require different resources or varying amounts of time.

**Threat Management**: The player needs to defend against attacks from the nearby villages. They may need to create defensive structures or even go on the offensive.

**Exploration & Expansion**: The player should have opportunities to explore and expand their territory. More territory means more resources, but also more potential threats.

**Research, Tech Tree**: Since DAVE-8782 is an alien AI, it would make sense to include technology upgrades. As DAVE-8782 collects more resources and learns more about human technology, he can make improvements to the mining, building, and combat capabilities of his enslaved workforce.

## Systems
**Terrain and Environment**: Iceland in 1400 would have a unique and interesting terrain. We can probably just do something simple for now, but some nice procgen would be cool

**UI for Task Management**: There should be a user-friendly way to allocate tasks to the enslaved humans. This could be through a menu or some form of point-and-click interface.

**Beacon and Enslaved Humans Visualization**: The beacons could be rendered as visible towers of light or some other distinct entity. There should also be visual cues to show when a human is enslaved or when they regain free will.

**Combat Mechanics**: Create visual effects for attacks, defensive structures, and combat animations. You could create a system where you can visibly see the health of your defensive structures.

**Exploration and Fog of War**: Implementing a system where the map is revealed as DAVE-8782 explores it can add a sense of discovery and excitement to the game.

**Comment by pwc** [comment]
My advice for improvement is that the existing pitch has insufficient lawsuits. I recommend adding more lawsuits, as were common in saga-period Iceland. This may require adjusting the setting back a few hundred years. This would allow DAVE to engage in diplomacy, which may be valuable for (a) dissuading attacks from competing villages, (b) persuading village(r)s to willing join the paperclip production effort, and (c) as a supplement or alternative to the combat system.

**Comment by kanerogers** [comment]
> My advice for improvement is that the existing pitch has insufficient lawsuits. I recommend adding more lawsuits, as were common in saga-period Iceland. This may require adjusting the setting back a few hundred years. This would allow DAVE to engage in diplomacy, which may be valuable for (a) dissuading attacks from competing villages, (b) persuading village(r)s to willing join the paperclip production effort, and (c) as a supplement or alternative to the combat system.

I think this is a fantastic idea!
